### ISSUE TITLE
'Eval' information of ASW dataset json file

### ISSUE THREAD

**Issue by DevKiHyun** [Jiang-Yidi/TS-TalkNet#2]
Hi!

Thanks to share your whole code!

I wonder that how did you do for 'eval' label (not 'label' label) in your evaluation.

As I know, eval 0 means that they will not use that frame which has 0 eval label for train and validation.

Thanks!

**Comment by Jiang-Yidi** [comment]
Hi,  we just excluded the frames with eval 0 to calculate the metric using the code like
`eval_Labels = np.array(Labels)[Evals==1]`
`eval_predScores = np.array(predScores)[Evals==1]`

**Comment by DevKiHyun** [comment]
Always thanks!
