### ISSUE TITLE
Speaker Recognition module pretrained model parameters

### ISSUE THREAD

**Issue by jclarke98** [Jiang-Yidi/TS-TalkNet#5]
Hi there,

Thanks for sharing your code - interesting stuff.

I was wondering if you could point me in the direction for the model parameters for the speaker encoder you used? Apologies in advance if this is something I have misunderstood or overlooked.

**Comment by Jiang-Yidi** [comment]
Hi, you can find the speaker encoder model here https://github.com/Jiang-Yidi/TS-TalkNet/blob/main/model/speakerEncoder.py#L87. And for the model checkpoint, I used this one: https://github.com/TaoRuijie/ECAPA-TDNN/blob/main/exps/pretrain.model.

Hope these can help.

**Comment by jclarke98** [comment]
My mistake, thank you!
